server:
  port: 3712

spring:
  application:
    name: notificacao-service

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:pulsecare}
    password: ${RABBITMQ_PASSWORD:pulsecare}
