server:
  port: 3711

spring:
  application:
    name: historico-service

  datasource:
    url: ${HISTORICO_DATASOURCE_URL:jdbc:postgresql://localhost:5432/historico_db}
    username: ${DB_USER:pulsecare}
    password: ${DB_PASSWORD:pulsecare}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:pulsecare}
    password: ${RABBITMQ_PASSWORD:pulsecare}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
